---
  - hosts: localhost
    connection: local
    become: true

    pre_tasks:
      - name: update repositories
        yum:
          update_cache: yes

    tasks:
      - include: tasks/packages.yml
      - include: tasks/nginx.yml
